# PROBLEM STATEMENT:
considering the social network advertisements data where an dataset should consist of the 5 columns named as user id,age,salary,gender and their rate of purchase(whether an person immediately purchased the product just by clicking upon an fancy advertisements generated in his/her social handles can be predicted by using the NAIVE BAYES classification Approach: 1.split the dataset into the dependent and independent variables by keenly understanding or observing the dataset. 2.Test and train the sample dataset where an test_size should be of 80-90% by default and training should be of 10% 3.Build an NaiveBayesmodel 4.Find the confusion _matrix score and accuracy_score.

# Importing the required libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the dataset

In [3]:
dataset=pd.read_csv('socialnetworksads.csv')

# Displaying the dataset

In [4]:
dataset.head()

USER ID  Gender  Age  EstimatedSalary  Purchased
0  15624501    MALE   19            19000          0
1  15810944    MALE   35            20000          0
2  15668575  FEMALE   26            43000          0
3  15603246  FEMALE   27            57000          0
4  15804002    MALE   19            76000          0

In [5]:
dataset.shape

(11, 5)

# Splitting of the datasets into an dependent and independent variables

In [6]:
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values


In [7]:
print(x)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]]


In [8]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0]


# Training and Testing the data

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=21)

# Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

# constructing an decision tree model

In [13]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# Prediction 

In [15]:
y_pred=classifier.predict(x_test)
print(y_pred)

[0 0 0]


# calculating the accuracy_score and creating an confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_pred,y_test)
ac=accuracy_score(y_pred,y_test)
print(cm,ac)

[[3]] 1.0
